plugins:
  commands.connection.connect:      {}
  commands.connection.disconnect:   {}
  commands.connection.is_connected: {}
  commands.project.open:            {}
  commands.project.is_open:         {}
  commands.project.name:            {}
  commands.project.read:            {}
  commands.project.close:           {}
  commands.project.calibration.apply:               {}
  commands.project.calibration.cal_groups:          {}
  # commands.project.calibration.cal_unit_autodetect: {}
  commands.project.calibration.cal_units:           {}
  commands.project.calibration.perform_step:        {}
  commands.project.calibration.start:               {}
  commands.project.calibration.step:                {}
  commands.project.calibration.steps:               {}
  commands.project.measurement.passed:         {}
  commands.project.measurement.perform_step:   {}
  commands.project.measurement.save:           {}
  commands.project.measurement.start:          {}
  commands.project.measurement.step:           {}
  commands.project.measurement.step_image:     {}
  commands.project.measurement.steps:          {}

devices: {}
# for troubleshooting:
preset:
  - vna: "*RST"
clear_status:
  - vna: "*CLS"
screen on:
  - vna: SYST:DISP:UPD {on}
local:
  - vna: "@LOC"
scpi_errors?:
  - vna: SYST:ERR?
service_function password function:
  - vna: SYST:PASS      '{password}'
  - vna: DIAG:SERV:SFUN '{function}'
