#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# exit on error
set -e

# build src/ui
cd $ROOT_DIR/src/ui
npm run build

# build server
cd $ROOT_DIR/server
ln -s $ROOT_DIR/src/ui/build site
pyinstaller --clean server.spec

# build desktop
cd $ROOT_DIR/desktop
# ln -s $ROOT_DIR/server/dist/test-automation server
mkdir -p server
cp -r $ROOT_DIR/server/dist/test-automation/* server/
npm run dist
