#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# exit on error
# echo on
set -e
set -x

# start test-automation server, webpack dev server
(trap 'kill 0' SIGINT; "$ROOT_DIR/server/dist/test-automation/test-automation" --http-only & "$ROOT_DIR/src/ui/scripts/start" >/dev/null 2>&1)
