#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# exit on error
# echo on
set -e
set -x

(trap 'kill 0' SIGINT; "$ROOT_DIR/server/dist/test-automation/test-automation" & "$ROOT_DIR/src/ui/scripts/start")
