#!/usr/bin/env bash

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$SCRIPTS_DIR/.."

# exit on error
# echo on
set -e
set -x

# build cable
cd "$ROOT_DIR/examples/cable"
zip -r ../cable.zip ./*
