#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# exit on error
# echo on
set -e
set -x

cd "$ROOT_DIR/.."
pip uninstall -y test-automation
rm -rf test_automation.egg-info
