#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# exit on error
# echo on
set -e
set -x

# clean
"$ROOT_DIR/clean"

# build
cd "$ROOT_DIR/.."
npm run build-dev && mv build build.dev
npm run build     && mv build build.prod
