#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# exit on error
# echo on
set -e
set -x

# clean
"$ROOT_DIR/clean"

# build
cd "$ROOT_DIR/.."
yarn build-dev
mv build build.dev
yarn build
mv build build.prod
