#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# exit on error
# echo on
set -e
set -x

cd "$ROOT_DIR/.."
npm install

# manually install lib/custom-create-react-app/packages/react-scripts
# by calling npm install again
# see https://github.com/npm/npm/issues/1341
cd node_modules/react-scripts
npm install
