#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# exit on error
# echo on
set -e
set -x

cd "$ROOT_DIR/.."
rm -rf node_modules
rm -rf lib/custom-create-react-app/packages/react-scripts/node_modules
