#!/usr/bin/env bash

ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# exit on error
# echo on
set -e
set -x

# build src/ui, server
"$ROOT_DIR/src/ui/scripts/build"
"$ROOT_DIR/server/scripts/build"

# NOT WORKING:
#   ln -s $ROOT_DIR/server/dist/test-automation server
# electron-builder won't follow symlink
mkdir -p "$ROOT_DIR/desktop/server"
cp -r "$ROOT_DIR/server/dist/test-automation/"* "$ROOT_DIR/desktop/server/"

# build desktop
"$ROOT_DIR/desktop/scripts/build"
