#!/usr/bin/env bash

# paths
SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$SCRIPTS_DIR/.."

# exit on error
# echo on
set -e
set -x

# clean
"$ROOT_DIR/src/server/scripts/clean"
"$ROOT_DIR/src/ui/scripts/clean"
"$ROOT_DIR/server/scripts/clean"
"$ROOT_DIR/desktop/scripts/clean"
